#!/bin/sh
sudo cp -f cinnamon-weather@mockturtl.gschema.xml /usr/share/glib-2.0/schemas/ &&
glib-compile-schemas --dry-run /usr/share/glib-2.0/schemas/ &&
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

sudo ln -sf ~/.local/share/cinnamon/applets/cinnamon-weather@mockturtl/cinnamon-weather-settings /usr/local/bin

TARGET=~/.local/share/cinnamon/applets/cinnamon-weather@mockturtl
rm -rf $TARGET
mkdir -p $TARGET
cp -f metadata.json applet.js cinnamon-weather-settings stylesheet.css $TARGET

./do-translation
